/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/ItemCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/ItemForm`; params?: Router.UnknownInputParams; } | { pathname: `/context/ItemsContext`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/item-form-screen`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/manage-options`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/view-items`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ItemCard`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ItemForm`; params?: Router.UnknownOutputParams; } | { pathname: `/context/ItemsContext`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/item-form-screen`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/manage-options`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/view-items`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/ItemCard${`?${string}` | `#${string}` | ''}` | `/components/ItemForm${`?${string}` | `#${string}` | ''}` | `/context/ItemsContext${`?${string}` | `#${string}` | ''}` | `/tabs/item-form-screen${`?${string}` | `#${string}` | ''}` | `/tabs/manage-options${`?${string}` | `#${string}` | ''}` | `/tabs/view-items${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/ItemCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/ItemForm`; params?: Router.UnknownInputParams; } | { pathname: `/context/ItemsContext`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/item-form-screen`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/manage-options`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/view-items`; params?: Router.UnknownInputParams; };
    }
  }
}
